version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/web/project.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm-alpine
    volumes:
      - .:/project