version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
  php:
    build: docker/fpm
    volumes:
      - .:/project
    links:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./app/setup/database:/docker-entrypoint-initdb.d
