version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
  php:
    build: docker/fpm
    volumes:
      - .:/project